### Geographic Segmentation using ANN

#### Data Description:

The dataset consists of 10000 records of a bank customers. The target variable being the status 'Exited' which says whether or 
not the customer left the bank.

#### Labels:

CustomerID  :  Unique ID of customer

Surname  :  Surname of Customer

CreditScore  :  Credit Score of customer

Geography  :  Country of residence of customer

Gender  :  Gender of customer

Age  :  Age of customer

Tenure  :  Time for which the customer was a member of the bank

Balance  :  Account Balance of the customer

NumofProducts  :  Num of products of the bank the customer is associated with

HasCrCard  :  Whether or not the customer has a credit card (1- Yes, 0- No)

IsActiveMember  :  If the customer is an active member of the bank (1- Yes, 0-No)

EstimatedSalary  :  Estimated salary of the bank customer

Exited  :  Whether or not the customer exited from the bank (1-Yes, 0-No)

In [97]:
#importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

%matplotlib inline

In [98]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [99]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [100]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [101]:
dataset.shape

(10000, 14)

In [102]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [103]:
# DATA PREPROCESSING


X = dataset.iloc[: , 3:13].values
y = dataset.iloc[:,13:].values

In [104]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [105]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int64)

In [106]:
X.shape , y.shape

((10000, 10), (10000, 1))

In [107]:
# ENCODING CATEGORICAL FEATURES

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
X[:, 2] = encoder.fit_transform(X[:, 2])

In [108]:
X[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [109]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [110]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [111]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),  [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [112]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [113]:
# SPLITTING DATASET INTO TRAIN AND TEST SET

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 101)

In [114]:
# FEATURE SCALING

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [115]:
X_train , X_train.shape

(array([[-1.01055571, -0.57504086,  1.74954671, ..., -1.55056613,
         -1.02199176,  0.74416401],
        [-1.01055571, -0.57504086,  1.74954671, ...,  0.64492573,
         -1.02199176, -1.59596268],
        [ 0.98955455, -0.57504086, -0.57157662, ...,  0.64492573,
          0.97848147,  0.02151338],
        ...,
        [-1.01055571,  1.73900686, -0.57157662, ...,  0.64492573,
          0.97848147,  0.65484524],
        [ 0.98955455, -0.57504086, -0.57157662, ...,  0.64492573,
          0.97848147,  0.72022509],
        [-1.01055571, -0.57504086,  1.74954671, ...,  0.64492573,
          0.97848147, -0.06269008]]),
 (8000, 12))

In [116]:
X_test, X_test.shape

(array([[-1.01055571, -0.57504086,  1.74954671, ...,  0.64492573,
          0.97848147,  0.39813382],
        [ 0.98955455, -0.57504086, -0.57157662, ...,  0.64492573,
          0.97848147, -0.65077449],
        [ 0.98955455, -0.57504086, -0.57157662, ..., -1.55056613,
          0.97848147,  1.23782388],
        ...,
        [ 0.98955455, -0.57504086, -0.57157662, ..., -1.55056613,
         -1.02199176, -1.3252864 ],
        [-1.01055571, -0.57504086,  1.74954671, ...,  0.64492573,
          0.97848147, -0.08060085],
        [-1.01055571, -0.57504086,  1.74954671, ..., -1.55056613,
         -1.02199176,  1.27418157]]),
 (2000, 12))

In [117]:
# BUILDING THE ARTIFICIAL NEURAL NETWORK

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [118]:
model = Sequential()

In [119]:
model.add(Dense(units = 8, activation = 'relu', input_dim = 12))
model.add(Dense(units = 12, activation = 'relu'))
model.add(Dense(units = 1, activation = 'sigmoid'))

In [120]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [121]:
model.fit(X_train, y_train, batch_size=32, epochs = 40)

Train on 8000 samples
Epoch 1/40
8000/8000 [==============================] - 0s 48us/sample - loss: 0.5458 - accuracy: 0.7605
Epoch 2/40
8000/8000 [==============================] - 0s 26us/sample - loss: 0.4602 - accuracy: 0.7983
Epoch 3/40
8000/8000 [==============================] - 0s 26us/sample - loss: 0.4393 - accuracy: 0.8024
Epoch 4/40
8000/8000 [==============================] - 0s 27us/sample - loss: 0.4262 - accuracy: 0.8149
Epoch 5/40
8000/8000 [==============================] - 0s 26us/sample - loss: 0.4121 - accuracy: 0.8263
Epoch 6/40
8000/8000 [==============================] - 0s 26us/sample - loss: 0.3941 - accuracy: 0.8376
Epoch 7/40
8000/8000 [==============================] - 0s 26us/sample - loss: 0.3760 - accuracy: 0.8485
Epoch 8/40
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3634 - accuracy: 0.8536
Epoch 9/40
8000/8000 [==============================] - 0s 27us/sample - loss: 0.3555 - accuracy: 0.8566
Epoch 10/40
8000/8000 [==========

In [122]:
# MAKING PREDICTIONS USING THE TRAINED ANN

predictions = model.predict(X_test)

In [123]:
predictions

array([[0.03733238],
       [0.03184462],
       [0.55452394],
       ...,
       [0.05485585],
       [0.2455728 ],
       [0.47443476]], dtype=float32)

In [127]:
predictions = np.round(predictions)

In [129]:
predictions

array([[0.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float16)

In [130]:
# COMPARING PREDICTIONS TO TRUE TEST VALUES

print(np.concatenate((predictions.reshape(len(predictions),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 1.]]


In [134]:
# EVALUATING MODEL PERFORMANCE USING CONFUSION MATRIX

from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, predictions)
accuracy = accuracy_score(y_test, predictions)

In [135]:
cm     # 1489 True positives and 242 True Negatives

array([[1498,   79],
       [ 181,  242]], dtype=int64)

In [136]:
accuracy # The model has an accuracy of 87%

0.87

## THE END